CREATE DATABASE MusicLog;
USE MusicLog;

CREATE TABLE usuarios (
idUsuarios INT PRIMARY KEY auto_increment,
nome VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
senha VARCHAR(20) NOT NULL
);

CREATE TABLE musicas (
idMusicas SERIAL PRIMARY KEY,
nome VARCHAR(45) NOT NULL,
artista VARCHAR(45) NOT NULL,
genero VARCHAR(30) NOT NULL,
nota SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
data_criacao TIMESTAMP NOT NULL DEFAULT NOW(),
data_edicao TIMESTAMP NOT NULL DEFAULT NOW()
);